version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwertyuiop

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080
